// <auto-generated />
using System;
using Gestion.Ganadera.Business.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestion.Ganadera.Business.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420004539_AddGanaderiaCore")]
    partial class AddGanaderiaCore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gestion.Ganadera.Business.Domain.Features.Ganaderia.Animal", b =>
                {
                    b.Property<long>("Animal_Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Animal_Codigo"));

                    b.Property<bool>("Animal_Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Animal_Fecha_Ingreso_Inicial")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Animal_Fecha_Registro_Ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime>("Animal_Fecha_Ultimo_Evento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Animal_Origen_Ingreso")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Animal_Sexo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("Categoria_Animal_Codigo")
                        .HasColumnType("bigint");

                    b.Property<long?>("Cliente_Codigo")
                        .HasColumnType("bigint");

                    b.Property<long>("Creado_Por")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Fecha_Creado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime?>("Fecha_Modificado")
                        .HasColumnType("datetime2");

                    b.Property<long>("Finca_Codigo")
                        .HasColumnType("bigint");

                    b.Property<long?>("Modificado_Por")
                        .HasColumnType("bigint");

                    b.Property<long>("Potrero_Codigo")
                        .HasColumnType("bigint");

                    b.HasKey("Animal_Codigo");

                    b.HasIndex("Categoria_Animal_Codigo");

                    b.HasIndex("Finca_Codigo");

                    b.HasIndex("Potrero_Codigo");

                    b.HasIndex("Cliente_Codigo", "Animal_Activo");

                    b.ToTable("Animal", "Ganaderia");
                });

            modelBuilder.Entity("Gestion.Ganadera.Business.Domain.Features.Ganaderia.CategoriaAnimal", b =>
                {
                    b.Property<long>("Categoria_Animal_Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Categoria_Animal_Codigo"));

                    b.Property<bool>("Categoria_Animal_Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria_Animal_Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Categoria_Animal_Orden")
                        .HasColumnType("int");

                    b.Property<string>("Categoria_Animal_Sexo_Esperado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("Cliente_Codigo")
                        .HasColumnType("bigint");

                    b.Property<long>("Creado_Por")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Fecha_Creado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime?>("Fecha_Modificado")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Modificado_Por")
                        .HasColumnType("bigint");

                    b.HasKey("Categoria_Animal_Codigo");

                    b.HasIndex("Cliente_Codigo", "Categoria_Animal_Nombre")
                        .IsUnique()
                        .HasFilter("[Cliente_Codigo] IS NOT NULL");

                    b.ToTable("Categoria_Animal", "Ganaderia");
                });

            modelBuilder.Entity("Gestion.Ganadera.Business.Domain.Features.Ganaderia.EventoDetalleRegistroExistente", b =>
                {
                    b.Property<long>("Evento_Ganadero_Codigo")
                        .HasColumnType("bigint");

                    b.Property<long>("Categoria_Animal_Codigo")
                        .HasColumnType("bigint");

                    b.Property<long?>("Cliente_Codigo")
                        .HasColumnType("bigint");

                    b.Property<long>("Creado_Por")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Evento_Detalle_Registro_Existente_Fecha_Informada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Evento_Detalle_Registro_Existente_Identificador_Valor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Evento_Detalle_Registro_Existente_Sexo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Fecha_Creado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime?>("Fecha_Modificado")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Modificado_Por")
                        .HasColumnType("bigint");

                    b.Property<long>("Potrero_Codigo")
                        .HasColumnType("bigint");

                    b.Property<long>("Rango_Edad_Codigo")
                        .HasColumnType("bigint");

                    b.Property<long>("Tipo_Identificador_Codigo")
                        .HasColumnType("bigint");

                    b.HasKey("Evento_Ganadero_Codigo");

                    b.HasIndex("Categoria_Animal_Codigo");

                    b.HasIndex("Potrero_Codigo");

                    b.HasIndex("Rango_Edad_Codigo");

                    b.HasIndex("Tipo_Identificador_Codigo");

                    b.ToTable("Evento_Detalle_Registro_Existente", "Ganaderia");
                });

            modelBuilder.Entity("Gestion.Ganadera.Business.Domain.Features.Ganaderia.EventoGanadero", b =>
                {
                    b.Property<long>("Evento_Ganadero_Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Evento_Ganadero_Codigo"));

                    b.Property<long?>("Cliente_Codigo")
                        .HasColumnType("bigint");

                    b.Property<long>("Creado_Por")
                        .HasColumnType("bigint");

                    b.Property<bool>("Evento_Ganadero_Es_Anulacion")
                        .HasColumnType("bit");

                    b.Property<bool>("Evento_Ganadero_Es_Correccion")
                        .HasColumnType("bit");

                    b.Property<string>("Evento_Ganadero_Estado")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("Evento_Ganadero_Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Evento_Ganadero_Fecha_Registro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Evento_Ganadero_Observacion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long?>("Evento_Ganadero_Origen_Codigo")
                        .HasColumnType("bigint");

                    b.Property<string>("Evento_Ganadero_Registrado_Por")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Evento_Ganadero_Tipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("Fecha_Creado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime?>("Fecha_Modificado")
                        .HasColumnType("datetime2");

                    b.Property<long>("Finca_Codigo")
                        .HasColumnType("bigint");

                    b.Property<long?>("Modificado_Por")
                        .HasColumnType("bigint");

                    b.HasKey("Evento_Ganadero_Codigo");

                    b.HasIndex("Evento_Ganadero_Origen_Codigo");

                    b.HasIndex("Finca_Codigo");

                    b.HasIndex("Cliente_Codigo", "Finca_Codigo", "Evento_Ganadero_Tipo", "Evento_Ganadero_Fecha");

                    b.ToTable("Evento_Ganadero", "Ganaderia");
                });

            modelBuilder.Entity("Gestion.Ganadera.Business.Domain.Features.Ganaderia.EventoGanaderoAnimal", b =>
                {
                    b.Property<long>("Evento_Ganadero_Animal_Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Evento_Ganadero_Animal_Codigo"));

                    b.Property<long>("Animal_Codigo")
                        .HasColumnType("bigint");

                    b.Property<long?>("Cliente_Codigo")
                        .HasColumnType("bigint");

                    b.Property<long>("Creado_Por")
                        .HasColumnType("bigint");

                    b.Property<string>("Evento_Ganadero_Animal_Estado_Afectacion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Evento_Ganadero_Animal_Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Evento_Ganadero_Animal_Orden")
                        .HasColumnType("int");

                    b.Property<long>("Evento_Ganadero_Codigo")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Fecha_Creado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime?>("Fecha_Modificado")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Modificado_Por")
                        .HasColumnType("bigint");

                    b.HasKey("Evento_Ganadero_Animal_Codigo");

                    b.HasIndex("Animal_Codigo");

                    b.HasIndex("Evento_Ganadero_Codigo", "Animal_Codigo")
                        .IsUnique();

                    b.ToTable("Evento_Ganadero_Animal", "Ganaderia");
                });

            modelBuilder.Entity("Gestion.Ganadera.Business.Domain.Features.Ganaderia.Finca", b =>
                {
                    b.Property<long>("Finca_Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Finca_Codigo"));

                    b.Property<long?>("Cliente_Codigo")
                        .HasColumnType("bigint");

                    b.Property<long>("Creado_Por")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Fecha_Creado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime?>("Fecha_Modificado")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Finca_Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Finca_Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("Modificado_Por")
                        .HasColumnType("bigint");

                    b.HasKey("Finca_Codigo");

                    b.HasIndex("Cliente_Codigo", "Finca_Nombre")
                        .IsUnique()
                        .HasFilter("[Cliente_Codigo] IS NOT NULL");

                    b.ToTable("Finca", "Ganaderia");
                });

            modelBuilder.Entity("Gestion.Ganadera.Business.Domain.Features.Ganaderia.IdentificadorAnimal", b =>
                {
                    b.Property<long>("Identificador_Animal_Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Identificador_Animal_Codigo"));

                    b.Property<long>("Animal_Codigo")
                        .HasColumnType("bigint");

                    b.Property<long?>("Cliente_Codigo")
                        .HasColumnType("bigint");

                    b.Property<long>("Creado_Por")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Fecha_Creado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime?>("Fecha_Modificado")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Identificador_Animal_Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("Identificador_Animal_Es_Principal")
                        .HasColumnType("bit");

                    b.Property<string>("Identificador_Animal_Valor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<long?>("Modificado_Por")
                        .HasColumnType("bigint");

                    b.Property<long>("Tipo_Identificador_Codigo")
                        .HasColumnType("bigint");

                    b.HasKey("Identificador_Animal_Codigo");

                    b.HasIndex("Animal_Codigo", "Tipo_Identificador_Codigo")
                        .IsUnique();

                    b.HasIndex("Tipo_Identificador_Codigo", "Identificador_Animal_Valor")
                        .IsUnique();

                    b.ToTable("Identificador_Animal", "Ganaderia");
                });

            modelBuilder.Entity("Gestion.Ganadera.Business.Domain.Features.Ganaderia.Potrero", b =>
                {
                    b.Property<long>("Potrero_Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Potrero_Codigo"));

                    b.Property<long?>("Cliente_Codigo")
                        .HasColumnType("bigint");

                    b.Property<long>("Creado_Por")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Fecha_Creado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime?>("Fecha_Modificado")
                        .HasColumnType("datetime2");

                    b.Property<long>("Finca_Codigo")
                        .HasColumnType("bigint");

                    b.Property<long?>("Modificado_Por")
                        .HasColumnType("bigint");

                    b.Property<bool>("Potrero_Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Potrero_Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Potrero_Codigo");

                    b.HasIndex("Finca_Codigo", "Potrero_Nombre")
                        .IsUnique();

                    b.ToTable("Potrero", "Ganaderia");
                });

            modelBuilder.Entity("Gestion.Ganadera.Business.Domain.Features.Ganaderia.RangoEdad", b =>
                {
                    b.Property<long>("Rango_Edad_Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Rango_Edad_Codigo"));

                    b.Property<long?>("Cliente_Codigo")
                        .HasColumnType("bigint");

                    b.Property<long>("Creado_Por")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Fecha_Creado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime?>("Fecha_Modificado")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Modificado_Por")
                        .HasColumnType("bigint");

                    b.Property<bool>("Rango_Edad_Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("Rango_Edad_Edad_Maxima_Meses")
                        .HasColumnType("int");

                    b.Property<int?>("Rango_Edad_Edad_Minima_Meses")
                        .HasColumnType("int");

                    b.Property<string>("Rango_Edad_Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Rango_Edad_Orden")
                        .HasColumnType("int");

                    b.HasKey("Rango_Edad_Codigo");

                    b.HasIndex("Cliente_Codigo", "Rango_Edad_Nombre")
                        .IsUnique()
                        .HasFilter("[Cliente_Codigo] IS NOT NULL");

                    b.ToTable("Rango_Edad", "Ganaderia");
                });

            modelBuilder.Entity("Gestion.Ganadera.Business.Domain.Features.Ganaderia.TipoIdentificador", b =>
                {
                    b.Property<long>("Tipo_Identificador_Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Tipo_Identificador_Codigo"));

                    b.Property<long?>("Cliente_Codigo")
                        .HasColumnType("bigint");

                    b.Property<long>("Creado_Por")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Fecha_Creado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime?>("Fecha_Modificado")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Modificado_Por")
                        .HasColumnType("bigint");

                    b.Property<bool>("Tipo_Identificador_Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Tipo_Identificador_Codigo_Interno")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Tipo_Identificador_Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("Tipo_Identificador_Operativo")
                        .HasColumnType("bit");

                    b.Property<bool>("Tipo_Identificador_Permite_Busqueda")
                        .HasColumnType("bit");

                    b.Property<bool>("Tipo_Identificador_Permite_Principal")
                        .HasColumnType("bit");

                    b.HasKey("Tipo_Identificador_Codigo");

                    b.HasIndex("Cliente_Codigo", "Tipo_Identificador_Nombre")
                        .IsUnique()
                        .HasFilter("[Cliente_Codigo] IS NOT NULL");

                    b.ToTable("Tipo_Identificador", "Ganaderia");
                });

            modelBuilder.Entity("Gestion.Ganadera.Business.Domain.Features.Navegacion.MenuNavegacion", b =>
                {
                    b.Property<long>("Menu_Navegacion_Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Menu_Navegacion_Codigo"));

                    b.Property<string>("Menu_Navegacion_Accion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Menu_Navegacion_Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Menu_Navegacion_Esta_Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Menu_Navegacion_Icono")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Menu_Navegacion_Orden")
                        .HasColumnType("int");

                    b.Property<long?>("Menu_Navegacion_Padre_Codigo")
                        .HasColumnType("bigint");

                    b.Property<string>("Menu_Navegacion_Permiso_Requerido")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Menu_Navegacion_Requiere_Cuenta_Padre")
                        .HasColumnType("bit");

                    b.Property<string>("Menu_Navegacion_Ruta")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Menu_Navegacion_Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Menu_Navegacion_Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Menu_Navegacion_Codigo");

                    b.HasIndex("Menu_Navegacion_Clave")
                        .IsUnique();

                    b.HasIndex("Menu_Navegacion_Padre_Codigo", "Menu_Navegacion_Orden");

                    b.ToTable("Menu_Navegacion", "Aplicacion");
                });

            modelBuilder.Entity("Gestion.Ganadera.Business.Domain.Features.Seguridad.Auditoria", b =>
                {
                    b.Property<long>("Auditoria_Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Auditoria_Codigo"));

                    b.Property<string>("Auditoria_Api_Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Auditoria_Fecha_Modificado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Auditoria_Modificado_Por")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Auditoria_Nombre_Tabla")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Auditoria_Nuevos_Valores")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Auditoria_Valor_Clave")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Auditoria_Valores_Viejos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Cliente_Codigo")
                        .HasColumnType("bigint");

                    b.HasKey("Auditoria_Codigo");

                    b.HasIndex("Cliente_Codigo");

                    b.ToTable("Auditoria", "Seguridad");
                });

            modelBuilder.Entity("Gestion.Ganadera.Business.Infrastructure.Observability.Models.LogAplicacion", b =>
                {
                    b.Property<long>("Log_Aplicacion_Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Log_Aplicacion_Codigo"));

                    b.Property<long?>("Cliente_Codigo")
                        .HasColumnType("bigint");

                    b.Property<string>("Log_Aplicacion_Api_Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Log_Aplicacion_Api_Codigo");

                    b.Property<string>("Log_Aplicacion_CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Log_Aplicacion_CorrelationId");

                    b.Property<string>("Log_Aplicacion_Excepcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Log_Aplicacion_Excepcion");

                    b.Property<DateTime>("Log_Aplicacion_Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("Log_Aplicacion_Fecha");

                    b.Property<string>("Log_Aplicacion_Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Log_Aplicacion_Mensaje");

                    b.Property<string>("Log_Aplicacion_Metodo")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("Log_Aplicacion_Metodo");

                    b.Property<string>("Log_Aplicacion_Nivel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("Log_Aplicacion_Nivel");

                    b.Property<string>("Log_Aplicacion_Origen")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("Log_Aplicacion_Origen");

                    b.Property<string>("Log_Aplicacion_Ruta")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Log_Aplicacion_Ruta");

                    b.Property<string>("Log_Aplicacion_Usuario")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Log_Aplicacion_Usuario");

                    b.HasKey("Log_Aplicacion_Codigo");

                    b.HasIndex("Cliente_Codigo");

                    b.HasIndex("Log_Aplicacion_Fecha");

                    b.HasIndex("Log_Aplicacion_Nivel", "Log_Aplicacion_Fecha");

                    b.ToTable("Log_Aplicacion", "Seguridad");
                });

            modelBuilder.Entity("Gestion.Ganadera.Business.Infrastructure.Observability.Models.MetricaSolicitud", b =>
                {
                    b.Property<long>("Metrica_Solicitud_Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Metrica_Solicitud_Codigo"));

                    b.Property<long?>("Cliente_Codigo")
                        .HasColumnType("bigint");

                    b.Property<string>("Metrica_Solicitud_Api_Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Metrica_Solicitud_Codigo_Estado")
                        .HasColumnType("int");

                    b.Property<string>("Metrica_Solicitud_Correlation_Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Metrica_Solicitud_Fecha_Creacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Metrica_Solicitud_Metodo_Http")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Metrica_Solicitud_Ruta_Request")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("Metrica_Solicitud_Tiempo_Respuesta_Ms")
                        .HasColumnType("bigint");

                    b.HasKey("Metrica_Solicitud_Codigo");

                    b.HasIndex("Cliente_Codigo");

                    b.ToTable("Metrica_Solicitud", "Seguridad");
                });

            modelBuilder.Entity("Gestion.Ganadera.Business.Infrastructure.Security.Models.EventoSeguridad", b =>
                {
                    b.Property<long>("Evento_Seguridad_Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Evento_Seguridad_Codigo"));

                    b.Property<long?>("Cliente_Codigo")
                        .HasColumnType("bigint");

                    b.Property<string>("Evento_Seguridad_Api_Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Evento_Seguridad_CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Evento_Seguridad_Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Evento_Seguridad_Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Evento_Seguridad_Ip")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Evento_Seguridad_Origin")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Evento_Seguridad_Tipo_Evento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Evento_Seguridad_UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Evento_Seguridad_Codigo");

                    b.HasIndex("Cliente_Codigo");

                    b.ToTable("Seguridad_Evento", "Seguridad");
                });

            modelBuilder.Entity("Gestion.Ganadera.Business.Domain.Features.Ganaderia.Animal", b =>
                {
                    b.HasOne("Gestion.Ganadera.Business.Domain.Features.Ganaderia.CategoriaAnimal", null)
                        .WithMany()
                        .HasForeignKey("Categoria_Animal_Codigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestion.Ganadera.Business.Domain.Features.Ganaderia.Finca", null)
                        .WithMany()
                        .HasForeignKey("Finca_Codigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestion.Ganadera.Business.Domain.Features.Ganaderia.Potrero", null)
                        .WithMany()
                        .HasForeignKey("Potrero_Codigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestion.Ganadera.Business.Domain.Features.Ganaderia.EventoDetalleRegistroExistente", b =>
                {
                    b.HasOne("Gestion.Ganadera.Business.Domain.Features.Ganaderia.CategoriaAnimal", null)
                        .WithMany()
                        .HasForeignKey("Categoria_Animal_Codigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestion.Ganadera.Business.Domain.Features.Ganaderia.EventoGanadero", null)
                        .WithMany()
                        .HasForeignKey("Evento_Ganadero_Codigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestion.Ganadera.Business.Domain.Features.Ganaderia.Potrero", null)
                        .WithMany()
                        .HasForeignKey("Potrero_Codigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestion.Ganadera.Business.Domain.Features.Ganaderia.RangoEdad", null)
                        .WithMany()
                        .HasForeignKey("Rango_Edad_Codigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestion.Ganadera.Business.Domain.Features.Ganaderia.TipoIdentificador", null)
                        .WithMany()
                        .HasForeignKey("Tipo_Identificador_Codigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestion.Ganadera.Business.Domain.Features.Ganaderia.EventoGanadero", b =>
                {
                    b.HasOne("Gestion.Ganadera.Business.Domain.Features.Ganaderia.EventoGanadero", null)
                        .WithMany()
                        .HasForeignKey("Evento_Ganadero_Origen_Codigo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Gestion.Ganadera.Business.Domain.Features.Ganaderia.Finca", null)
                        .WithMany()
                        .HasForeignKey("Finca_Codigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestion.Ganadera.Business.Domain.Features.Ganaderia.EventoGanaderoAnimal", b =>
                {
                    b.HasOne("Gestion.Ganadera.Business.Domain.Features.Ganaderia.Animal", null)
                        .WithMany()
                        .HasForeignKey("Animal_Codigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestion.Ganadera.Business.Domain.Features.Ganaderia.EventoGanadero", null)
                        .WithMany()
                        .HasForeignKey("Evento_Ganadero_Codigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestion.Ganadera.Business.Domain.Features.Ganaderia.IdentificadorAnimal", b =>
                {
                    b.HasOne("Gestion.Ganadera.Business.Domain.Features.Ganaderia.Animal", null)
                        .WithMany()
                        .HasForeignKey("Animal_Codigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestion.Ganadera.Business.Domain.Features.Ganaderia.TipoIdentificador", null)
                        .WithMany()
                        .HasForeignKey("Tipo_Identificador_Codigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestion.Ganadera.Business.Domain.Features.Ganaderia.Potrero", b =>
                {
                    b.HasOne("Gestion.Ganadera.Business.Domain.Features.Ganaderia.Finca", null)
                        .WithMany()
                        .HasForeignKey("Finca_Codigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestion.Ganadera.Business.Domain.Features.Navegacion.MenuNavegacion", b =>
                {
                    b.HasOne("Gestion.Ganadera.Business.Domain.Features.Navegacion.MenuNavegacion", null)
                        .WithMany()
                        .HasForeignKey("Menu_Navegacion_Padre_Codigo")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
