// <auto-generated />
using System;
using Gestion.Ganadera.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestion.Ganadera.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409040039_FixMenuNavigationTitles")]
    partial class FixMenuNavigationTitles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gestion.Ganadera.Domain.Features.Navegacion.MenuNavegacion", b =>
                {
                    b.Property<long>("Menu_Navegacion_Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Menu_Navegacion_Codigo"));

                    b.Property<string>("Menu_Navegacion_Accion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Menu_Navegacion_Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Menu_Navegacion_Esta_Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Menu_Navegacion_Icono")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Menu_Navegacion_Orden")
                        .HasColumnType("int");

                    b.Property<long?>("Menu_Navegacion_Padre_Codigo")
                        .HasColumnType("bigint");

                    b.Property<string>("Menu_Navegacion_Permiso_Requerido")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Menu_Navegacion_Requiere_Cuenta_Padre")
                        .HasColumnType("bit");

                    b.Property<string>("Menu_Navegacion_Ruta")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Menu_Navegacion_Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Menu_Navegacion_Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Menu_Navegacion_Codigo");

                    b.HasIndex("Menu_Navegacion_Clave")
                        .IsUnique();

                    b.HasIndex("Menu_Navegacion_Padre_Codigo", "Menu_Navegacion_Orden");

                    b.ToTable("Menu_Navegacion", "Aplicacion");
                });

            modelBuilder.Entity("Gestion.Ganadera.Domain.Features.Seguridad.Auditoria", b =>
                {
                    b.Property<long>("Auditoria_Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Auditoria_Codigo"));

                    b.Property<string>("Auditoria_Api_Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Auditoria_Fecha_Modificado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Auditoria_Modificado_Por")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Auditoria_Nombre_Tabla")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Auditoria_Nuevos_Valores")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Auditoria_Valor_Clave")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Auditoria_Valores_Viejos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Cliente_Codigo")
                        .HasColumnType("bigint");

                    b.HasKey("Auditoria_Codigo");

                    b.HasIndex("Cliente_Codigo");

                    b.ToTable("Auditoria", "Seguridad");
                });

            modelBuilder.Entity("Gestion.Ganadera.Infrastructure.Observability.Models.LogAplicacion", b =>
                {
                    b.Property<long>("Log_Aplicacion_Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Log_Aplicacion_Codigo"));

                    b.Property<long?>("Cliente_Codigo")
                        .HasColumnType("bigint");

                    b.Property<string>("Log_Aplicacion_Api_Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Log_Aplicacion_Api_Codigo");

                    b.Property<string>("Log_Aplicacion_CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Log_Aplicacion_CorrelationId");

                    b.Property<string>("Log_Aplicacion_Excepcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Log_Aplicacion_Excepcion");

                    b.Property<DateTime>("Log_Aplicacion_Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("Log_Aplicacion_Fecha");

                    b.Property<string>("Log_Aplicacion_Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Log_Aplicacion_Mensaje");

                    b.Property<string>("Log_Aplicacion_Metodo")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("Log_Aplicacion_Metodo");

                    b.Property<string>("Log_Aplicacion_Nivel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("Log_Aplicacion_Nivel");

                    b.Property<string>("Log_Aplicacion_Origen")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("Log_Aplicacion_Origen");

                    b.Property<string>("Log_Aplicacion_Ruta")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Log_Aplicacion_Ruta");

                    b.Property<string>("Log_Aplicacion_Usuario")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Log_Aplicacion_Usuario");

                    b.HasKey("Log_Aplicacion_Codigo");

                    b.HasIndex("Cliente_Codigo");

                    b.HasIndex("Log_Aplicacion_Fecha");

                    b.HasIndex("Log_Aplicacion_Nivel", "Log_Aplicacion_Fecha");

                    b.ToTable("Log_Aplicacion", "Seguridad");
                });

            modelBuilder.Entity("Gestion.Ganadera.Infrastructure.Observability.Models.MetricaSolicitud", b =>
                {
                    b.Property<long>("Metrica_Solicitud_Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Metrica_Solicitud_Codigo"));

                    b.Property<long?>("Cliente_Codigo")
                        .HasColumnType("bigint");

                    b.Property<string>("Metrica_Solicitud_Api_Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Metrica_Solicitud_Codigo_Estado")
                        .HasColumnType("int");

                    b.Property<string>("Metrica_Solicitud_Correlation_Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Metrica_Solicitud_Fecha_Creacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Metrica_Solicitud_Metodo_Http")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Metrica_Solicitud_Ruta_Request")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("Metrica_Solicitud_Tiempo_Respuesta_Ms")
                        .HasColumnType("bigint");

                    b.HasKey("Metrica_Solicitud_Codigo");

                    b.HasIndex("Cliente_Codigo");

                    b.ToTable("Metrica_Solicitud", "Seguridad");
                });

            modelBuilder.Entity("Gestion.Ganadera.Infrastructure.Security.Models.EventoSeguridad", b =>
                {
                    b.Property<long>("Evento_Seguridad_Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Evento_Seguridad_Codigo"));

                    b.Property<long?>("Cliente_Codigo")
                        .HasColumnType("bigint");

                    b.Property<string>("Evento_Seguridad_Api_Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Evento_Seguridad_CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Evento_Seguridad_Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Evento_Seguridad_Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Evento_Seguridad_Ip")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Evento_Seguridad_Origin")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Evento_Seguridad_Tipo_Evento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Evento_Seguridad_UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Evento_Seguridad_Codigo");

                    b.HasIndex("Cliente_Codigo");

                    b.ToTable("Seguridad_Evento", "Seguridad");
                });

            modelBuilder.Entity("Gestion.Ganadera.Domain.Features.Navegacion.MenuNavegacion", b =>
                {
                    b.HasOne("Gestion.Ganadera.Domain.Features.Navegacion.MenuNavegacion", null)
                        .WithMany()
                        .HasForeignKey("Menu_Navegacion_Padre_Codigo")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
