// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Gestion.Ganadera.Infrastructure.Persistence;

#nullable disable

namespace Gestion.Ganadera.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gestion.Ganadera.Domain.Features.Seguridad.Auditoria", b =>
                {
                    b.Property<long>("Auditoria_Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Auditoria_Codigo"));

                    b.Property<string>("Auditoria_Api_Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Auditoria_Fecha_Modificado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Auditoria_Modificado_Por")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Auditoria_Nombre_Tabla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Auditoria_Nuevos_Valores")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Auditoria_Valor_Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Auditoria_Valores_Viejos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Auditoria_Codigo");

                    b.ToTable("Auditoria", "Seguridad");
                });

            modelBuilder.Entity("Gestion.Ganadera.Infrastructure.Observability.Models.MetricaSolicitud", b =>
                {
                    b.Property<long>("Metrica_Solicitud_Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Metrica_Solicitud_Codigo"));

                    b.Property<string>("Metrica_Solicitud_Api_Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Metrica_Solicitud_Codigo_Estado")
                        .HasColumnType("int");

                    b.Property<string>("Metrica_Solicitud_Correlation_Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Metrica_Solicitud_Fecha_Creacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Metrica_Solicitud_Metodo_Http")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Metrica_Solicitud_Ruta_Request")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("Metrica_Solicitud_Tiempo_Respuesta_Ms")
                        .HasColumnType("bigint");

                    b.HasKey("Metrica_Solicitud_Codigo");

                    b.ToTable("Metrica_Solicitud", "Seguridad");
                });

            modelBuilder.Entity("Gestion.Ganadera.Infrastructure.Security.Models.EventoSeguridad", b =>
                {
                    b.Property<long>("Evento_Seguridad_Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Evento_Seguridad_Codigo"));

                    b.Property<string>("Evento_Seguridad_Api_Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Evento_Seguridad_CorrelationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Evento_Seguridad_Endpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Evento_Seguridad_Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Evento_Seguridad_Ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Evento_Seguridad_Origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Evento_Seguridad_Tipo_Evento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Evento_Seguridad_UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Evento_Seguridad_Codigo");

                    b.ToTable("Seguridad_Evento", "Seguridad");
                });
#pragma warning restore 612, 618
        }
    }
}
